// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9Tr5_jIYrNmRopI0hmgjLzLIOdWtngQ',
    appId: '1:703146092890:web:b1de7949e2f2c71994ab63',
    messagingSenderId: '703146092890',
    projectId: 'todo-app-60a4a',
    authDomain: 'todo-app-60a4a.firebaseapp.com',
    storageBucket: 'todo-app-60a4a.appspot.com',
    measurementId: 'G-3ETXPC1ET2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnFGanlV2bOSTe0yXL3Dxap5vYIajC9YM',
    appId: '1:703146092890:android:015d7cfdf3d73e3594ab63',
    messagingSenderId: '703146092890',
    projectId: 'todo-app-60a4a',
    storageBucket: 'todo-app-60a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56zxSZpJJCNq13HymGkkiIezd-Ycxx2A',
    appId: '1:703146092890:ios:b6f63508982ed8ca94ab63',
    messagingSenderId: '703146092890',
    projectId: 'todo-app-60a4a',
    storageBucket: 'todo-app-60a4a.appspot.com',
    iosBundleId: 'com.example.todoProjectTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56zxSZpJJCNq13HymGkkiIezd-Ycxx2A',
    appId: '1:703146092890:ios:b2a43772ae753e3694ab63',
    messagingSenderId: '703146092890',
    projectId: 'todo-app-60a4a',
    storageBucket: 'todo-app-60a4a.appspot.com',
    iosBundleId: 'com.example.todoProjectTask.RunnerTests',
  );
}
